[[casacore]]
arch = "aarch64"
git-tree-sha1 = "db5e76fefb4aae6632bf77f1fd09da8d7dcd0ec4"
libgfortran_version = "5.0.0"
os = "macos"

    [[casacore.download]]
    sha256 = "f57a2e6b7d31133311f58dff070a9e610f44bca7490394dccd0ee7128e29211f"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48f315f4fae16f6487ace3969d6398cf032e7ec7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "f089fb3be14f7a4bdd117dd53e98ebf95aa997a8c79c973a30327ca63d28759b"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.aarch64-linux-gnu-libgfortran3-cxx03.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f1ed1aadffcba3cd95f2fd654c889ff76c95178"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "4e39c683fac43450fad0f00a46a2e6c7525569111a60ddd4f1fe12ffb1d14da0"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.aarch64-linux-gnu-libgfortran3-cxx11.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3221d6ce426e673438ee49029c9cdbcc4441f6d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "2d309c00d519bf8f086f5781e924feec5ea2d7f3fa3c41a3e54901c563ae4433"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.aarch64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0172cdf069988e8dac4ee1d8084056219c30728"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "65f794e5f48ffbd763e3619d5c5306c151b891cea7db78024a9504c3c201776b"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.aarch64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b1bcc8c696b4a98a5ed762b69d93a572951d996"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "b70d8adb8ac7f88fd909e1d62c6fcb48daf842af78c6bc14560a3724ce0e50b8"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.aarch64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13d09260fb6aa05576fdd98d1439eca333dc9c7d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "2ea1602db013a19a8e14f868f22be6a6d9d9d66e0f1797d5750d161f5e6cdbcd"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "864be00ea2965bad878517aeda849eb6e96a1ca0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "aaf66ae261529a2f367e6ac673ca03b8ba36340ef109647b1ef60eab01634b20"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv6l-linux-gnueabihf-libgfortran3-cxx03.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a79999b498337005fdfa2c27461823aac50d5bc6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "453f2c44d4b3b2149c7aa04ec6423b99f577c32d6441e883c2edc3ae070cbaeb"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv6l-linux-gnueabihf-libgfortran3-cxx11.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd919d5a01e803798b8f5afa5129e88818e42fb6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "38e48cee525a1a82b223f7350541135b1cd8bec62b4a4c0e28ac6594d70efda0"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv6l-linux-gnueabihf-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4eb273f8f35523a72a754cf1931e72a66deca85"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "149d9f2f4fa9b01940dc5bcfe79146fc8eb746b4244b206a4855dd6e9782c050"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv6l-linux-gnueabihf-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea32ca4427814595721724429aaf8b7cccaa1d2a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "5789ab8e0c313cd966f525251250be32f7785cbff3a98d71e0ac574bb39450ee"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv6l-linux-gnueabihf-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99977795c410467c1a02ee4b00b6affe086608a1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "bdd798fb0084e655eeca7fe29799ad18ba36af8e928bdb58fc1b5c4f43fed186"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdf0580c3f36fe176907e71321fb8ffe0312a891"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "cc68bfda3ac80124ffdf40b6e944566a1fd2f330b0157258c7d7131189e55df4"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv7l-linux-gnueabihf-libgfortran3-cxx03.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "263defae09e5574417ac8011b9f91dd258f495dc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "7fd4a0dd9eb1a0c702f2c4a06e91b60fed8152d27ec19b15139ee298d0eb6fd1"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv7l-linux-gnueabihf-libgfortran3-cxx11.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "daea4bd15857d3d1d3c5a40cae75dcd4bb70ba7f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "5d6ddf5f39fc60b2e894820845217e5c9b4ee67e1a841a439c15ba9bfc6a9b57"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv7l-linux-gnueabihf-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f64c0af12a70318059866056ddfdc38232045f1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "0fcc1ad9d2515f35f942baf64868bec39efad87bdf054aef37fffe7637dbefa4"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv7l-linux-gnueabihf-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2059fcf90d4e8f39f653bbbe51642e25cab6c0f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "054d279941269c942ce965144e8b97a3235b548980da1f4ed0c975e791b72c92"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv7l-linux-gnueabihf-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe4bdf59f1fac5572f71973d15970db5ba133750"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "1f3db4d8d1623effc55a3fc0acb007252aa7b4dd5bfe6e4daa1412e0b746e7c9"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ad010110a6cc97f7c3470f74ec7f6f9aef0af1f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "e6bcd2a1ed77046fcebd3c4c82bf66af4aad519f92ce8425f5fefea5a78dbc0b"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.i686-linux-gnu-libgfortran3-cxx03.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2111060ca7894c32011d22a741d08a37abef0fc0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "65471cd3c753c6ae14c98905bd8ac61cecec2bbc46bf3606c4783655b2ba07ae"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.i686-linux-gnu-libgfortran3-cxx11.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88c638d360b33a94911ab4a93401a5eeda2a0e8b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "9edeecb1fb5d1df13fb96dc15dd0863acf5b1f17723334592bad0c4b40aeb895"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.i686-linux-gnu-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea1b9610880b1f3da0c129ab8c4e22eb7c78396c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "fc4e6b25ee55d586599774b4d609c5e3379081cdbdbc8cf43bff55f95c5bdea9"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.i686-linux-gnu-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b64338dea391f184591f8a8aefa9c39918085162"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "79ca8af5106c563bcf316f2c57d84f127b76074dc54b3d4e82fe29056d5e7cc2"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.i686-linux-gnu-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e5341ef76ef04fb2fad7b39c12891416cf50aa2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "61d219249b6851c35623aec413bc633a04eb904b149c34fa050e62f5d5e080d4"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[casacore]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f596b7b1253e71adf5a300d5701ebc936a099a3e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "85f6ab3539fc059e7a2897a28cfaf7c6481bec9b1f8f5377fbb0d61aebd15fdc"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.powerpc64le-linux-gnu-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6923c2dbe9cc229d67ccbe6749be36fc4ccf539d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "4907a0e861c36c1f6db709a17afac6614d7e104233f18a8358043c66ffb1f65c"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.powerpc64le-linux-gnu-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0c3dfb13de023b28005f94af516076ee195ecc9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "56600c014a527636c513490479634254a15bddf0f1b320876850a9b4ffe6cc5a"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.powerpc64le-linux-gnu-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10fce97574aa862adaf65e6c971169c2d1e1942a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "de8f16b908538272e0cd29a15f7383a4659b075c0bdf75d05ec9f6195f0603a2"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[casacore]]
arch = "x86_64"
git-tree-sha1 = "7b135624edf36fd7ca64ec1ac7fabe65c395ce87"
libgfortran_version = "3.0.0"
os = "macos"

    [[casacore.download]]
    sha256 = "a54d47afdf2a90de77128ea1eae8b9f1761d22faaf71c040686823461517cc99"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[casacore]]
arch = "x86_64"
git-tree-sha1 = "7614d0d6deef1d47c1f1779b9863867e197f8675"
libgfortran_version = "4.0.0"
os = "macos"

    [[casacore.download]]
    sha256 = "b69c7ea10c822fbaca70ea80b18cf18566e62a6faaabbb740fdd527d220ff4bb"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[casacore]]
arch = "x86_64"
git-tree-sha1 = "24d2553f52de5fdb4d2385f5cd01ca680ecd843d"
libgfortran_version = "5.0.0"
os = "macos"

    [[casacore.download]]
    sha256 = "8927f3655d03f0b029271d9928c950ee731c5f632a2fc65278a0a9bf752df215"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5cc570022e0151513c56b1b1907967f14ca3fdd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "4023ffefe6f5472df9765087e485847d346e481822e7a61dcd0a31d19e474a36"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.x86_64-linux-gnu-libgfortran3-cxx03.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0966b73336293f07b1c95ae5f31677188b629162"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "e9d96882ded99ec67cf2baa65c8bb98fb217fe3c68a2200d7952b490863e3724"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.x86_64-linux-gnu-libgfortran3-cxx11.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6c8d7cb69ec3158e27695327781f03c58ccda43"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "6579a29f9f0088d5fc149a9d31f831a0d268534279150bbf45a242d1a8a6580e"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.x86_64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b38f1a6c521b388bd71c7cc90b29477c1bdcc6cd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "e472e47bff215ee7cb885b1fe9537cb55124dbed9438ccb7db6b8240b0be4a87"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11890156134948e4109161231c438c8aa0b3636f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "57210f56ce072fe91af2103d3cfe99abfa652da978e98c56d18a4b1e1f0199cf"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.x86_64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9501f83e605d8126473708d879a4085f475d198d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "321e3d767208ba6b2bcc39e19964ec37197caf76def381688c73a2b9215e248f"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.0+0/casacore.v3.5.0.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
