[[casacore]]
arch = "aarch64"
git-tree-sha1 = "7e7d8a6bdf5128c65225a0f8e67f0548b2f809c0"
libgfortran_version = "5.0.0"
os = "macos"

    [[casacore.download]]
    sha256 = "b343ed31275b08cad652cf6911aeaa33f4b552b74dce606bf1d77eec3a4060d2"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e115c4060f75c9d9bda6201d317a97534907901"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "a8a18b006b548da0880acd5c7875589859f49d9b1a926ef0d20c2f192af043a4"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.aarch64-linux-gnu-libgfortran3-cxx03.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "791120cae7adc95ea838d8fb50ac4f29f1a4d35b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "229da6c1f025209aa11a02b71b932a1da910892d9ba07169b080faedb27cd994"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.aarch64-linux-gnu-libgfortran3-cxx11.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5df5098ea8ab7c58b96c21be7ff26ab48f8cc9eb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "87f58bef5058f6327a36d59764ae1c0394f3bce2053b21d33668f4f3cd599d16"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.aarch64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c054c5cbeaeb576b59099c574d0265f1c9c53a79"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "10476aa0e32395f25ce5ffb7a8ebe4f1f71f4ab3d61dd28d4fca9d18f338286f"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.aarch64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bedb0949c0d21b383611c66545850c9825ca9152"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "36cd2cf3b1256996cd8cb4ce96380f28be3680f553b22c0e2cf3ea01fe71d25b"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.aarch64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8e4fc2c2bf0c1e8687d13b83f3c78fd447db253"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "60fd6723dea6706fbcb4926f645f1507a045e6020a1bb1c68ff0118fbdad4a46"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b45e18769597a408daa0f9abd967c9153cfdb58b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "575918accda130f5ded149ed49a8e9bbfafc71d7569ae9cefb3dca40b7712e83"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv6l-linux-gnueabihf-libgfortran3-cxx03.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e1b877f66d26e1432e260d4d2469844ff43367a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "442d2531e618d9450c6079e182f7339df55baf3c7d64a0351111b6a34b8e415a"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv6l-linux-gnueabihf-libgfortran3-cxx11.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f02bfc9ad3a78c880bc3bc74830e00e733da1e1a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "1bd18a980096ad008619bdae26781ebd299ab88cdfacd01f2267ea28fbf859e6"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv6l-linux-gnueabihf-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "336b04174818bd849ba3b4d2050ef604b25bf549"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "0e6bc53c080f57423f404bc5dd6a6d1ec9e76520e23a0fe009659a6beed52d5a"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv6l-linux-gnueabihf-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78a06e530f1c66f9dd30fe4271f123da2873ee0d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "a1379b334a5dc4b8e9daed0a78dcccfc59d3033169456098e4aa728c02fa1780"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv6l-linux-gnueabihf-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1dd021cfd88726cd93c6e05e74418ca976b39a4b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "3f3276aed49acf872bc057702d5f60a0052cedcd4a17087481ddec38776bdf15"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2cbc69e60ead61b5e99c0f4b9f0a8847f05093b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "0809bbd7e68d7d6513ef88f0c3b255be9b44541e82aba7dfd353ae151a6ea871"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv7l-linux-gnueabihf-libgfortran3-cxx03.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5a577671506257f9df216ef29970639bff0bbaf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "974fd69887e955207d441f0b5a5a62fb789afcb4eb22a2204ed6da9fb75b85db"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv7l-linux-gnueabihf-libgfortran3-cxx11.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08c7470dcc138ed817d74c45f89447990789107a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "ecba5a9eca8d10c34383b771e3261bb6496ea83323a7c27cfaacdf94ab162d46"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv7l-linux-gnueabihf-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46315c82bddee23e475f2a68b49cf15daa1a7958"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "1eff208bb04109de29f9784a54bf28c95a6b0cf64ef01b633f13a0280988eb6a"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv7l-linux-gnueabihf-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f48c5db2984cc1ccb26d5b514a5369bbfba7cfe1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "a249b89a92505fb5bc161f57b06b8dd2986985a06898fc211ddbb3f606763369"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv7l-linux-gnueabihf-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b7890a03569568dfcaa95280f72a5ab2c8367e2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "204293adeb2072371a433d271365d3cd7ef1743c0ded87aacd9c0c140ccb056b"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9131f4b6d40819fa55c8beb6b32aac69ff9bc684"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "cec5ae7169ceedfa7812b9b42e6595e01e9ae46daeef10822fb0a9f7587e1a4f"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.i686-linux-gnu-libgfortran3-cxx03.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9121ab21e583640ec5730ff3e5481068993c7519"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "cce7dbdbe5d377bab57c44f530ba53f39d186024415cac3145f5e81fe3eccfdd"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.i686-linux-gnu-libgfortran3-cxx11.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6c863ec8054b4ff05242def0c2420c3ef4d6a67"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "cf4ab9f110b6a712628d61521f6e5d1e1a27e3b04086fea4840a41fe505fe02a"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.i686-linux-gnu-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ea1f49dfeef03b4d7100b6d8eb424598ff7bceb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "633d896a1365cf4c8d888d2087f55f93cdbd573447fc8952563943dec53861b9"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.i686-linux-gnu-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e2db7ba66847ec53009bb29b5e7f99d8ae2ffa3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "eee7d1f976d4f0d694b00ca7fc197b18fd95544bc6517479a7b09a6a476b6219"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.i686-linux-gnu-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cff2675cec66dfb29145e3c39e257246c981d1a8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "78bbbc9431d177fffcf5459b51f6f5b5385f5394b8151300a082c172126bb59d"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[casacore]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbd9fa8bf6a522b0ae23aebe79cc2dd6eed6fa16"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "f407a687d19a1c80e2b5b946c8491df23eeb6f5a7a559ee20ec3a723258c48f1"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.powerpc64le-linux-gnu-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79123801aaf4968de8355a163c8ea4f6c1ae1a1f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "1a07e2f3b73110fc1a723a2559bddf78ad71881bf21e467fb99c4c7a96de6598"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.powerpc64le-linux-gnu-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2396ac3c8caa06c9b961515fd78908fcb5c4019c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "e6387bb0ef33e5d605d1b2dee7354c4d856e8c4d04611511d6cdaa753e383123"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.powerpc64le-linux-gnu-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d93d045fb92df83b0a111b542f2d25925cf4857d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "153c089b58a21c01fff6e1c5e7d4e33f79f14189505a4cdfbfc42e5370fd14bf"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[casacore]]
arch = "x86_64"
git-tree-sha1 = "82a9b33092a0bd2aaacf7a175523bc1ae5c2eacb"
libgfortran_version = "3.0.0"
os = "macos"

    [[casacore.download]]
    sha256 = "c1fff8784a370b11be44403f358fc1d49408e897284d166e8a675ab1895733c3"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[casacore]]
arch = "x86_64"
git-tree-sha1 = "ce573b90c9e133d067117279061a846e9832692e"
libgfortran_version = "4.0.0"
os = "macos"

    [[casacore.download]]
    sha256 = "1354437e1744c1ff2762426937f232141e1b703fa12521e35b76de54d8b63dbc"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[casacore]]
arch = "x86_64"
git-tree-sha1 = "d4597f86156fc83c34c399f3dfc2338d34ce9aa8"
libgfortran_version = "5.0.0"
os = "macos"

    [[casacore.download]]
    sha256 = "207a1b05603e26b21494abdbc97e0e8461c46f60b138d67be9e24bb2af3931e6"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d425b4edc2a7b9abb5c7f414259c72b2a36027ad"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "b1d84ce83dfa66c77e5971321739cbf896954778f855e9c63f2c682ae7b7a15e"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.x86_64-linux-gnu-libgfortran3-cxx03.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43a3f02d2c0fea0a7f122c26f2d20f42903fc596"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "25e3cb4d8c7de3f4f719e73310fe2befe17a90ddbc3814637a0c1994a99b7747"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.x86_64-linux-gnu-libgfortran3-cxx11.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2d6fa2d8bbd357c842b9e98b33ea979d49fe285"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "e3950f019571f32cbadbc8d0746da7e4a93afdbd63a9ff17f3d8ffe3d0f212c8"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.x86_64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a66f53bf49bd9d7efc41418911703cd1b1cce9cc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "c0b397eff3452b02d48accfa4502e858e0046db37771d89ea500b0cc54db6f04"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc8899aef94e348e961c2b8a29605f6f2bc12e31"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "aee91e103b6134fc44d322af4003f139c3aebd9af30c7d65bb284bce643be002"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.x86_64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[casacore]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "284db20f5e28d2acbc70c9a4b530c3d700a4a9aa"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[casacore.download]]
    sha256 = "ec71ebc62fd32d683f9bce558cb552eb69a2a9ae5a4a2b3f5f39ede8741be077"
    url = "https://github.com/JuliaBinaryWrappers/casacore_jll.jl/releases/download/casacore-v3.5.1+0/casacore.v3.5.1.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
